# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Juniors', 'Juniors'), ('Adults', 'Adults')], default='', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='quality',
            field=models.TextField(null=True),
        ),
    ]
