# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200110_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adults',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='juniors',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
