# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200114_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='product',
            name='juniors',
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.CharField(choices=[('Juniors', 'Juniors'), ('Adults', 'Adults')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Juniors', 'Juniors'), ('Adults', 'Adults')], default='', max_length=254),
        ),
    ]
