# Generated by Django 2.0.2 on 2020-01-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='productcomment',
            name='products',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
