# Generated by Django 3.0.2 on 2020-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Juniors', 'Juniors'), ('Adults', 'Adults')], max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.CharField(max_length=254),
        ),
    ]
