# Generated by Django 3.0.2 on 2020-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(choices=[('5.00', '5.00'), ('10.00', '10.00')], decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Almost New', 'Almost New'), ('Used Boots', 'Used Boots')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='studs',
            field=models.CharField(choices=[('Screw in', 'Screw in'), ('Moulded', 'Moulded')], max_length=50),
        ),
    ]
